name: CI/CD Node.js a Render
 
on:
  push:
    branches:
      - main
 
jobs:
  test:
    name: Ejecutar pruebas
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
 
      - name: Instalar Node.js
        uses: actions/setup-node@v4
 
        with:
          node-version: 24
 
      - name: Instalar dependencias
        run: npm install
 
      - name: Ejecutar pruebas
        run: npm test
 
  deploy:
    name: Desplegar en Render
 
    needs: test
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Ejecutar Deploy Hook de Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"